### ISSUE TITLE
compatible with QGIS 1.9.0 ?

### ISSUE THREAD

**Issue by pauljweaver** [lutraconsulting/os2ogr#4]
Cant get the plugin to install with latest qgis weekly build - 1.9.0-Master. After adding the repository and manually copying os2ogr folder to plugins directory it now says it is incompatible with this version of QGIS (Plugin designed for QGIS 1.5.0 - 1.99) and displays in red. Am I missing something obvious (qgis beginner here)?

**Comment by mostlyAtNight** [comment]
Hi pauljweaver,

os2ogr has been developed for the latest stable version of QGIS (1.8) and I suspect that the latest unstable (development version) has a different API, making the plugin incompatible at this stage.  This has been added to a list of topics to cover at the upcoming QGIS developer conference so I suspect that the issue will be resolved in the coming month or so.

**Comment by pauljweaver** [comment]
Thanks for that - I'll stick with 1.8 for now then !
